import PySimpleGUI as sg
import os

def create_python_file(filename):
    # Generate the Python file with the given filename
    with open(filename, "w") as file:
        file.write("# Python file generated by PySimpleGUI\n")
        file.write(f"def {filename[:-3]}():\n")
        file.write("    # TODO: Implement the functionality\n")
        file.write("    print(f'{filename} function called')\n")

def handle_button_click(event):
    # Handle button click event here
    create_python_file(f"{event}.py")
    print(f"Button '{event}' clicked. Python file generated.")

def show_buttons():
    # Create the buttons
    button_clientes = sg.Button("Clientes", size=(15, 2))
    button_fornecedores = sg.Button("Fornecedores", size=(15, 2))
    button_funcionarios = sg.Button("Funcionarios", size=(15, 2))
    button_produtos = sg.Button("Produtos", size=(15, 2))
    button_vendedores = sg.Button("Vendedores", size=(15, 2))
    button_usuarios = sg.Button("Usúarios", size=(15, 2))
    button_transportadoras = sg.Button("Transportadoras", size=(15, 2))
    button_cidades = sg.Button("Cidades", size=(15, 2))

    # Create the button layout
    button_layout = [
        [button_clientes, button_fornecedores, button_funcionarios],
        [button_produtos, button_vendedores, button_usuarios],
        [button_transportadoras, button_cidades]
    ]

    # Create the main layout
    layout = [
        [sg.Text("Selecione uma opção:", size=(20, 1), justification="center", font=("Helvetica", 14))],
        [sg.Col(button_layout, justification="center")]
    ]

    # Create the main window
    window = sg.Window("Cadastros", layout, finalize=True)

    # Start the main loop
    while True:
        event, values = window.read()
        if event is None:
            break

        handle_button_click(event)

    window.close()

if __name__ == "__main__":
    show_buttons()
